version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  test-postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test-password
      POSTGRES_DB: test_db
    ports:
      - "5430:5432"  # Map host port 5430 to container port 5432
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
